// fetch posts
export const POSTS_FETCH_STARTED = 'POSTS_FETCH_STARTED';
export const POSTS_FETCH_COMPLETED = 'POSTS_FETCH_COMPLETED';
export const POSTS_FETCH_ERROR = 'POSTS_FETCH_ERROR';
export const POSTS_FETCH_RESET = 'POSTS_FETCH_RESET';

// create post
export const POSTS_CREATE_STARTED = 'POSTS_CREATE_STARTED';
export const POSTS_CREATE_COMPLETED = 'POSTS_CREATE_COMPLETED';
export const POSTS_CREATE_ERROR = 'POSTS_CREATE_ERROR';
export const POSTS_CREATE_RESET = 'POSTS_CREATE_RESET';

// get post by id
export const POSTS_GET_BY_ID_STARTED = 'POSTS_GET_BY_ID_STARTED';
export const POSTS_GET_BY_ID_COMPLETED = 'POSTS_GET_BY_ID_COMPLETED';
export const POSTS_GET_BY_ID_ERROR = 'POSTS_GET_BY_ID_ERROR';
export const POSTS_GET_BY_ID_RESET = 'POSTS_GET_BY_ID_RESET';

// update post
export const POSTS_UPDATE_STARTED = 'POSTS_UPDATE_STARTED';
export const POSTS_UPDATE_COMPLETED = 'POSTS_UPDATE_COMPLETED';
export const POSTS_UPDATE_ERROR = 'POSTS_UPDATE_ERROR';
export const POSTS_UPDATE_RESET = 'POSTS_UPDATE_RESET';

// delete post
export const POSTS_DELETE_STARTED = 'POSTS_DELETE_STARTED';
export const POSTS_DELETE_COMPLETED = 'POSTS_DELETE_COMPLETED';
export const POSTS_DELETE_ERROR = 'POSTS_DELETE_ERROR';
export const POSTS_DELETE_RESET = 'POSTS_DELETE_RESET';
